feat: CU-jd52b5 create Tag
genstackio/libs-js pull request #2
Opened 2021-05-06 15:56 UTC by koala819

2021-05-06 15:56 UTC, ohoareau commented
Task linked: [CU-jd52b5 Composant Tag](https://app.clickup.com/t/jd52b5)

2021-05-06 16:01 UTC, ohoareau requested changes

2021-05-06 16:01 UTC, ohoareau commented on packages/react-admin-ui/src/atoms/Tag.tsx
> +            <svg
Aucun code svg ou image en dur dans le code des composants.

2021-05-07 07:44 UTC, koala819 commented on packages/react-admin-ui/src/atoms/Tag.tsx
> +            <svg
OK je vais créer un fichier svg à part

2021-05-07 10:08 UTC, merged