feat: CU-kz6hm7_Composant-Molecules--Charts--RateChart
genstackio/libs-js pull request #63
Opened 2021-06-04 14:29 UTC by federica-buzzi

2021-06-04 14:29 UTC, ohoareau commented
Task linked: [CU-kz6hm7 Composant Molecules > Charts > RateChart](https://app.clickup.com/t/kz6hm7)

2021-06-07 15:08 UTC, carl-mrchnd requested changes

2021-06-07 15:08 UTC, carl-mrchnd commented on packages/react-admin-ui/__stories__/molecules/RateChart.stories.tsx
> +        series: args.series,
tu peux rajouter value, title, subtitle, overline et enlever series

2021-06-07 16:24 UTC, carl-mrchnd approved these changes

2021-06-07 16:40 UTC, ohoareau approved these changes

2021-06-07 16:40 UTC, merged