feat: CU-m3e5c0_Composant-Molecules--Charts--ArcChart
genstackio/libs-js pull request #69
Opened 2021-06-08 08:21 UTC by federica-buzzi

2021-06-08 08:21 UTC, ohoareau commented
Task linked: [CU-m3e5c0 Composant Molecules > Charts > ArcChart](https://app.clickup.com/t/m3e5c0)

2021-06-08 15:05 UTC, carl-mrchnd requested changes

2021-06-08 15:05 UTC, carl-mrchnd commented on packages/react-admin-ui/__stories__/molecules/ArcChart.stories.tsx
> +        series: args.series,
tu peux remplacer series par value ici

2021-06-09 07:00 UTC, ohoareau approved these changes

2021-06-09 07:00 UTC, ohoareau commented on packages/react-admin-ui/src/molecules/ArcChart.tsx
> +export interface ArcChartProps {s
`{s` => `{`

2021-06-09 07:00 UTC, merged