feat: CU-kz6tj3 create ProductCardBlock
genstackio/libs-js pull request #71
Opened 2021-06-08 09:47 UTC by koala819

2021-06-08 09:47 UTC, ohoareau commented
Task linked: [CU-kz6tj3 Composant Organisms > Blocks > ProductCardBlock](https://app.clickup.com/t/kz6tj3)

2021-06-08 15:10 UTC, carl-mrchnd requested changes

2021-06-08 15:10 UTC, carl-mrchnd commented on packages/react-admin-ui/__stories__/organisms/Blocks/ProductCardBlock.stories.tsx
> +        color: args.color,
tu peux rajouter les props description, image, price,... ici

2021-06-08 16:48 UTC, carl-mrchnd approved these changes

2021-06-09 07:10 UTC, ohoareau approved these changes
Bravo !

2021-06-09 07:16 UTC, merged